### ISSUE TITLE
database file not available

### ISSUE THREAD

**Issue by belicks1999** [DeelakaLakpura/POINT-OF-SALES-SYSTEM#3]
can you send me the db file or query

**Comment by binhdtcs** [comment]
Can you send me the db

**Comment by germain219** [comment]
can you send me the db file or query

**Comment by onebird100** [comment]
can you send me the database file as well

**Comment by AkiraMaharaj** [comment]
Hi same for me pls

**Comment by fevzikartal** [comment]
Hi Deelaka Lakpura

Can you send me the db file or query

**Comment by Raj9417** [comment]
@belicks1999 di you get the database file? If yes please share it.

**Comment by Raj9417** [comment]
Please go to Pull Request of this repositories and check the CLosed case. The script is there.
